# Generated by Django 3.2.1 on 2021-07-01 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id_Calificacion', models.AutoField(primary_key=True, serialize=False)),
                ('calif_Unidad', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_Perfil', models.AutoField(primary_key=True, serialize=False)),
                ('contrasena', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_Usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=100)),
                ('edad', models.IntegerField(max_length=10)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id_Evaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('no_Evaluacion', models.IntegerField()),
                ('nombre_Evaluacion', models.CharField(max_length=20)),
                ('no_Aciertos', models.IntegerField()),
                ('respuestas_correctas', models.IntegerField()),
                ('calificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.calificacion')),
            ],
        ),
    ]
